# Documento de configuracion de servicios
# Se asumen por defecto contentype: application/json; charset=utf-8 y datatype: json 
# (En una proxima version se extendera la funcionalidad)

#Primer servicio
#s_1: 
#  name: registrar_vendedor
#  url: /vendedor/registrar
#  type: post
#  input:  
#    - codigo
#    - pass
#    - julieta : 
#        - edad
#        - peso
#        - perfil:
#            - situacion
#        - colegio:    
#            municipio: 
#            - dsd
#  output:
#    - status
# 
##Segundo servicio
#s_2:
#  name: verificar_vendedor
#  url: /vendedor/verificar
#  type: post
#  input:
#    - codigo
#    - pass
#  output:
#    - status

#Tercer servicio
s_1:
  name: agendar_sesiones
  url: /sesion/agendar
  headers: x-access-token
  type: post
  input:
   sesion:
    - titulo
    - descripcion
    - color
    - textcolor
    - inicio
    - anfitrion
  output:
    - status
    